# Generated by Django 5.0.6 on 2024-06-28 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJ_DRF_Test', '0002_remove_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assigned', to='DJ_DRF_Test.customuser'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидает исполнителя'), ('IN_PROGRESS', 'В процессе'), ('COMPLETED', 'Выполнена')], default='PENDING', max_length=20),
        ),
    ]
