# Generated by Django 5.0.6 on 2024-06-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJ_DRF_Test', '0004_customuser_photo'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('can_accept_task', 'Can accept task'), ('can_change_task_status', 'Can change task status'), ('can_view_all_tasks', 'Can view all tasks')]},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_user_permissions', to='auth.permission'),
        ),
    ]
