# Generated by Django 5.0.6 on 2024-06-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJ_DRF_Test', '0006_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='employee',
            new_name='assigned_to',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='customer',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_employee',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Заказчик'), ('employee', 'Сотрудник')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
