# Generated by Django 5.0.6 on 2024-06-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJ_DRF_Test', '0007_alter_task_options_rename_employee_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Заказчик'), ('employee', 'Сотрудник')], default='customer', max_length=10),
        ),
    ]
